// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://example.com/terms",
        "contact": {
            "name": "Rajip Upreti",
            "email": "upretirajeev0@gmail.com"
        },
        "license": {
            "name": "Proprietary"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "get": {
                "description": "Creates a one-time OIDC transaction and redirects the browser to Keycloak.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Start login",
                "parameters": [
                    {
                        "type": "string",
                        "example": "/dashboard",
                        "description": "Safe application-relative path after login",
                        "name": "return_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to the Keycloak authorization endpoint",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Could not start authentication",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Deletes the current session when present and always clears the session cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Log out",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.LogoutResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the user associated with the Redis-backed application session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.CurrentUserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/auth.SwaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/auth.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "API health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.HealthResponse"
                        }
                    }
                }
            }
        },
        "/health/auth": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Authentication health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpresponse.DependencyHealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.CurrentUserResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "type": "string",
                    "example": "2026-07-22T01:00:00Z"
                },
                "user": {
                    "$ref": "#/definitions/user.User"
                }
            }
        },
        "auth.LogoutResponse": {
            "type": "object",
            "properties": {
                "loggedOut": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "auth.SwaggerErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/httpresponse.ErrorDetail"
                }
            }
        },
        "httpresponse.DependencyHealthResponse": {
            "type": "object",
            "properties": {
                "clientId": {
                    "type": "string",
                    "example": "crm-backend"
                },
                "issuer": {
                    "type": "string",
                    "format": "uri",
                    "example": "http://localhost:8081/realms/crm"
                },
                "redirectUrl": {
                    "type": "string",
                    "format": "uri",
                    "example": "http://localhost:8080/auth/callback"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "httpresponse.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "authentication_required"
                },
                "message": {
                    "type": "string",
                    "example": "authentication is required"
                }
            }
        },
        "httpresponse.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "user.Status": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "SUSPENDED",
                "DELETED"
            ],
            "x-enum-varnames": [
                "StatusActive",
                "StatusSuspended",
                "StatusDeleted"
            ]
        },
        "user.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2026-07-21T01:00:00Z"
                },
                "displayName": {
                    "type": "string",
                    "example": "Local Developer"
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "developer@example.com"
                },
                "emailVerified": {
                    "type": "boolean",
                    "example": true
                },
                "firstName": {
                    "type": "string",
                    "example": "Local"
                },
                "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "3ea55be2-3e57-4c85-9d19-f6048c405e44"
                },
                "lastName": {
                    "type": "string",
                    "example": "Developer"
                },
                "status": {
                    "enum": [
                        "ACTIVE",
                        "SUSPENDED",
                        "DELETED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.Status"
                        }
                    ],
                    "example": "ACTIVE"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2026-07-21T01:00:00Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "Cookie",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "CRM Platform API",
	Description:      "Backend API for CRM authentication, users, organisations, contacts, deals, and related resources.\nAuthentication uses a Redis-backed opaque session stored in an HttpOnly cookie.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
