FROM golang:1.26-alpine

WORKDIR /workspace/apps/api

RUN apk add --no-cache \
    git \
    curl \
    ca-certificates

RUN go install github.com/air-verse/air@latest

COPY apps/api/go.mod apps/api/go.sum ./

RUN go mod download

CMD ["air", "-c", ".air.toml"]